### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Denwen12** [iniguezdj/fantasy-football-team-builder#1]
How can i try this out on my debian system?

**Comment by iniguezdj** [comment]
You could try NodeJS on Debian with something like this: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-10

**Comment by Denwen12** [comment]
im still new debian, i see you got something about web app , does that work

**Comment by iniguezdj** [comment]
The web app is a work in progress and should be ready later this year.

**Comment by iniguezdj** [comment]
Web app version available at [suirad.com](http://suirad.com)

**Comment by Denwen12** [comment]
cool im going to check it out

**Comment by Denwen12** [comment]
can you include a csv option to download all player projections?
